### ISSUE TITLE
alignZeros is not working

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#728]
Hi,

I have problem with alignZeros functionality for 2 y-axes. They are not aligning. Left one works fine with min: 0, but right one seems to be aligned to 1 instead of 0.

Here's jsbin showing the problem.
http://jsbin.com/loyegubamo

--
Thanks,
Adam

**Comment by AdamNowaczyk** [comment]
Hi Alex,

Any update on this issue?

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

Sorry, I'm really busy with the 4.0 release. I'll have to add this to that as there will not be an intermittent release for network and timeline. 

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Alex,

Ok. I'll be waiting. Good luck with 4.0 release. Keep up the good work :D.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam, 

This has been fixed in the v4 branch. It'll be included in the release.

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Alex,

Great news. I've been waiting for this fix. When do you plan to offically release v4?

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

Within 1 or 2 weeks. 

Regards

**Comment by AdamNowaczyk** [comment]
Alex,

I've cloned v4 branch and checked it with my current code, but it looks like I still have the issue:
![image](https://cloud.githubusercontent.com/assets/5577457/7493340/3f1e15a8-f400-11e4-8c52-45dd4c9534c3.png)

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
hmm.... Could you make a jsbin for this? It worked correctly in my tests..

**Comment by AdamNowaczyk** [comment]
Sorry, I used files directly from dist folder without 'npm run build' and it was code from 04/28. Now I've build it, so it's up to date, but now I'm getting this:
![image](https://cloud.githubusercontent.com/assets/5577457/7493701/5782e8fa-f403-11e4-898e-20e6e88fe8db.png)

I'm using dataAxis.customRange.left.min = 0 and it doesn't seem to be working, even for 'single y-axis':
![image](https://cloud.githubusercontent.com/assets/5577457/7493723/84c14668-f403-11e4-8796-a12d8c2e13a1.png)

Any ideas what might be wrong?

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam, 

I'll look into it. At least the align zero's is working :) I think the problem is that we have modified the option structure so the options you used uptil now are not nessecarily valid anymore (hence 4.0, its breaking so major release). We have to update docs for all modules. You'd be amazed how much time goes into docs!

I'd recommend you wait for the release.

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Alex,

I know how much time goes into the docs. Just wanted to share my findings. I'll definitely wait for the release. I really like visjs and I'm very greatful for you hard work. Maybe I'll be able to help somehow :D.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

You can look through the documentation on the v4 branch if you want, we could use some proofreading on the new format :). Network, timeline and graph2d have been updated, allthough it still needs some unifying css.

In case you're bored ;)

Cheers

**Comment by AdamNowaczyk** [comment]
Alex,

I've just updated the v4 code. I'll have a look in some free time, but that might not happen soon :D. I'll try to sync my code with v4 and see if the bugs were fixed (I'll follow new docs). I'll try to keep you informed :D.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
