### ISSUE TITLE
Nodes and Labels are not redrawn

### ISSUE THREAD

**Issue by Tooa** [almende/vis#974]
Hi,

When the zoom is applied and nodes are added to a dataset, the nodes are not redrawn until you move the mouse or zoom out.

See [this](https://github.com/Tooa/angular-visjs-playground) Code for the problem. Just start the application with http-server and go to http://localhost:8080/ in your web browser. 

Do the following to reproduce the problem:

* Zoom in (Scroll wheel). It's enough, when all labels are visible.
* Move the slider in the upper right corner to the right. You will notice, that nodes are removed from the graph. This works pretty well!
* Now move the slider back to the left. Problem observation: Nodes and labels disappear. Zoom out or mouse moving will redraw the graph.

Why does this work for removing nodes, but not for adding nodes?

Best Uli

**Comment by AlexDM0** [comment]
Hi,

Using the dataset is small examples all functions (update add and remove) are triggering redraws.

Can you reproduce this without using angular? If so we can fix it, if not then the issue is with the angular vis project I'm afraid. I'm not sure why you closed the issue there? 

Regards

**Comment by Tooa** [comment]
Hi Alex, 

I will try to reproduce this problem without angular. I further closed the other issue, because I thought it needs to be related to visjs. This was based on two assumptions: 

* The angular-visjs project is just wrapping the events. 
* The case `newValue > oldValue` (slider to the right) works, but the `newValue < oldValue` (slider to the left) case not. The only difference here is the called visjs method remove and update respectively. 

        $scope.$watch(
                function() {
                    return $scope.importance;
                },
            function(newValue, oldValue) {

                if(newValue != undefined) {

                if(newValue > oldValue) {
                    var nodesToRemove = $scope.graphData.nodes.get({
                        filter: function (item) {
                            return (item.value < newValue);
                        }
                    });
                    $scope.graphData.nodes.remove(nodesToRemove);
                } else if(newValue < oldValue) {
                    console.log("Origin: "  + $scope.nodes.length)
                    var nodesToAdd = $scope.nodes.get({
                        filter: function (item) {
                            return (item.value >= newValue);
                        }
                    });
                    $scope.graphData.nodes.update(nodesToAdd);
                }
            }
        });

**Comment by Tooa** [comment]
Hi Alex, 

I found the problem. In the case `newValue < oldValue`, it will also add nodes to the dataset that are already present. Adding a check for the node existence works for me.

    self.nodes = new VisDataSet(self.nodesArray);
    self.originNodes = jQuery.extend(true, {}, self.nodes);
    [...]
    else if(newValue < oldValue) {
            var nodesToAdd = self.originNodes.get({
                filter: function (item) {
                    return (item.value >= newValue && self.nodes.get(item.id) === null);
                }
            });
            self.nodes.update(nodesToAdd);
        }

Hope this helps to identify the problem. It would be also cool to have a `contains` method on the dataset to prevent calls like `self.nodes.get(item.id) === null`.

**Comment by AlexDM0** [comment]
Hi,

The contains call could be useful, I agree. Do I conclude correctly that the problem is not with vis?

Regards,

Alex

**Comment by Tooa** [comment]
> Do I conclude correctly that the problem is not with vis?

No, I think it's a problem with visjs. You should be able to reproduce it like the following:

* Apply a zoom to the graph to see every label
* Remove some nodes from the underlying node dataset
* Re-add the removed nodes to the dataset, <b>but also add nodes that were already in the node dataset and where not previously removed from it</b>. 

Maybe the problem also occurs, if you only have a zoom applied and add nodes to the dataset that are already present.

**Comment by AlexDM0** [comment]
I see now, I think this is due to the fact that you disabled the physics. 

I pushed a fix to develop, could you check if it solved the problem for you?

Regards

**Comment by Tooa** [comment]
Yes, the fix works :) As always, thanks for your help! Best Uli

**Comment by Tooa** [comment]
Hi Alex, 

I'm facing another problem that could be related to this issue. The use case is like the following:

* Move a node (physics disabled) to another position
* Remove nodes from the node dataset,  <b> especially the dragged node! </b>
* Re-add these nodes

What you will end up with looks the the following:

![Image](http://oi61.tinypic.com/25a6lo9.jpg)

**Comment by AlexDM0** [comment]
Hi,

It would really help if you could show me this in working code... I can't do anything with just a picture. I don't know which version you're using, but if I were to guess, it's not from the develop branch because I noticed this there before the fix and after it was fixed. If that is the case, then yes, it's the same issue.

Regards

**Comment by Tooa** [comment]
Sry, you're right. Basically it's the same code I showed in this ticket. I'm also using the latest version of the develop branch, but I still have this issue. For some nodes it works, right. But for the most not. It's definitely not working for leaf nodes. Couldn't find a pattern.

**Comment by Tooa** [comment]
Hi Alex,

I created a [fsFiddle](http://jsfiddle.net/bokm6ymy/11/) for you to find the problem. You can reproduce it like the following:

* Drag the node "Axel Springer" (in the picture near the big node "Google" which is the yellow group) to the left e.g like in the picture above. 
* Move the upper slider to the right. Nodes will be removed, including the node "Axel Springer".
* Move the second slider to the left. Nodes will be added again. You will see the situation in the picture above. 

Best Uli

**Comment by Tooa** [comment]
@AlexDM0 are you able to reproduce the problem? Not sure, if you got the message notification, because the ticket is already closed.

**Comment by AlexDM0** [comment]
Hi Uli,

We get emails on every change, no worries. I am handling multiple projects and I don't have time until next week to check the pile of issues that is ever growing :)

Regards

**Comment by Tooa** [comment]
Hehe, no problem :) A growing pile of issues is also something good. It simple means visjs is getting a lot of attention. You are doing very well and the project itself has a lot of cool unique features compared to the other libraries out there.

**Comment by AlexDM0** [comment]
Hi,

This is fixed in the develop branch.

For future reference, this is a small example of the issue:
http://jsbin.com/dipositowi/1/edit?html,output

Regards

**Comment by Tooa** [comment]
Hi,

thanks you! Will take the small example for future bug reports :)

**Comment by Tooa** [comment]
Hi Alex, 
could it be, that there is another redraw event missing for node images? I have the same problem as in the first post. The only difference this time is, that the nodes have an image attribute assigned. It's basically the same procedure to reproduce:  remove nodes, re-add nodes. If you don't have immediately an idea, I could try to provide a jsFiddle.

**Comment by Tooa** [comment]
Hi Alex,

are you able to reproduce this? No problem, if you have no time at the moment. Just want to make sure, you have it on your list. 

Best Uli

**Comment by AlexDM0** [comment]
Hi Uli,

Could you make this into a small example like the one I showed you last time? It would make finding the issue much easier.

Regards

**Comment by Tooa** [comment]
Yes, sry. [Here](http://jsbin.com/tebicozuke/1/edit?html,output) it is. Best Uli

**Comment by AlexDM0** [comment]
Hi Uli,

Thanks for the small example. Allthough I cant see it here anymore? Anyway, this is not a bug.

What you do is: you delete a node with id 2. That node is now gone, not hidden, gone. You then add a new node with id:2. It has no label, no shape so it defaults to a blue eclipse with no text, looking like a dot.

This is what you should do:
http://jsbin.com/kogepoxaxo/1/edit?html,output

Regards

**Comment by Tooa** [comment]
Yes, wait. I was kinda in a hurry and did it wrong. [Here](http://jsfiddle.net/bokm6ymy/15/) is the right small example. Apply the zoom, so all labels are visible. Move the upper slider to the right (nothing will be removed), then move the other slider to the left. All existing nodes will be updated and you will notice, that the images are gone.

**Comment by AlexDM0** [comment]
Hi Uli,

Thanks for the update. I managed to track it down. 

I have pushed a fix to develop, it should work now.

Cheers

**Comment by Tooa** [comment]
Hi Alex, 

thanks for fixing it :) Works now for me!

Best Uli
